# SPDX-FileCopyrightText: 2020 (c) Carl Schwan <carl@carlschwan.eu>
# SPDX-FileCopyrightText: 2020 (c) Matthieu Gallien <matthieu_gallien@yahoo.fr>
#
# SPDX-License-Identifier: CC0-1.0

variables:
  PRODUCT: Frameworks

include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-reuse.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml

linux kf5-qt5 qt5.15:
  image: "kdeorg/ci-suse-qt515"
  extends: .linux
  only:
    - master
    - merge_requests
  variables:
    PLATFORM: SUSEQt5.15
    BRANCH_GROUP: kf5-qt5

